name: 'Build and Export Godot Projects'
description: 'Automatically build and export Godot projects based on export presets.'
inputs:
  godot-version:
    description: 'The version of Godot Engine to use.'
    required: true
  project-path:
    description: 'Path to the Godot project directory. Defaults to the current directory.'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/export-godot.sh
      env:
        GODOT_VERSION: '${{ inputs.godot-version }}'
        PROJECT_PATH: '${{ inputs.project-path }}'
      shell: bash
