name: 'Build and Export Godot Projects'
description: 'Automatically build and export Godot projects based on export presets.'
inputs:
  godot-version:
    description: 'The version of Godot Engine to use.'
    required: true
  project-path:
    description: 'Path to the Godot project directory.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
      wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip
      unzip Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip
      chmod +x Godot_v${{ inputs.godot-version }}-stable_linux.x86_64
      cd ${{ inputs.project-path }}
      while IFS= read -r line; do
        if [[ $line == name* ]]; then
          preset_name=$(echo $line | cut -d'=' -f2 | tr -d '"')
        fi
        if [[ $line == export_path* ]]; then
          export_path=$(echo $line | cut -d'=' -f2 | tr -d '"')
          mkdir -p $(dirname $export_path)
          ../Godot_v${{ inputs.godot-version }}-stable_linux.x86_64 --headless --export-release "$preset_name" "$export_path" --quit
          if [ ! "$(ls -A $export_path)" ]; then
            echo "Export directory $export_path is empty."
            exit 1
          fi
          echo "Exported $preset_name to $export_path"
        fi
      done < export_presets.cfg
      shell: bash
